# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Shuangjie You's Personal Website"
description              : "Current Computer Science @Gatech, ex-MD Anderson Cancer Center, ex-Tencent."
repository               : "ShuangjieYou/acad-homepage.github.io"  # Replace with your GitHub repository
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      : "UA-XXXXXXXXX-X"  # Replace with your actual Google Analytics ID

# SEO Related
google_site_verification :  # Add if using Google Search Console
bing_site_verification   :  # Add if using Bing Webmaster Tools
baidu_site_verification  :  # Add if using Baidu Webmaster Tools

# Site Author
author:
  name             : "Shuangjie You"
  avatar           : "assets/images/profile_picture.png"  # Add your profile image here
  bio              : "Seeking SDE intern for summer 2025 and PhD opportunities for fall 2025."
  location         : "Atlanta, GA, USA"
 # employer         : "Your Employer"  # Optional
 # pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=-CBGDcUAAAAJ&hl=en"
  email            : "youshuangjie@gmail.com"
  researchgate     :  # Add if you have a ResearchGate profile
  uri              : 
  github           : "https://github.com/Jessie-You-97"
  linkedin         : "https://www.linkedin.com/in/jessie-sjyou/"
  orcid            : # e.g., "https://orcid.org/xxxx"
  twitter          : # Add if you have a Twitter profile

# Reading Files
include:
  - .htaccess
  - _pages
  - files

exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Gemfile
  - README
  - node_modules

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/New_York  # Atlanta follows Eastern Time (ET)

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
